### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by frasertweedale** [qfpl/dollaridoos#2]
I would like to see this lib on {h,st}ackage.  Alas, *money* is taken, as is *simple-money* and *safe-money*.

Some ideas:

- *money-wrapped*
- *money-arithmetic*
- *moneta* (https://en.wiktionary.org/wiki/money#Etymology)

**Comment by frasertweedale** [comment]
ping @gwils... chosen a new name yet? :)

**Comment by gwils** [comment]
Changed to "dollaridoos"
