### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by gwils** [qfpl/dollaridoos#3]
It would be good to set up some kind of continuous integration for this project so that pull requests are compiled and that sort of thing. Travis seems to be a popular thing for this? I should go and learn how to use it or another tool.

**Comment by gwils** [comment]
https://github.com/hvr/multi-ghc-travis

**Comment by frasertweedale** [comment]
@gwils have a look at the .travis.yml in some of my repos e.g.

- https://github.com/frasertweedale/hs-jose/blob/master/.travis.yml
- https://github.com/frasertweedale/hs-merkle-tree/blob/master/.travis.yml
